/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Edit;

/**
 *
 * @author Daan
 */
public class EditCustomer extends javax.swing.JFrame {

    /**
     * Creates new form EditCustomer
     */
    public EditCustomer() {
        initComponents();
        init();
    }
    
    public void init(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postalCodeTextEdit = new javax.swing.JTextField();
        lastNameTextEdit = new javax.swing.JTextField();
        phoneLabelEdit = new javax.swing.JLabel();
        residenceTextEdit = new javax.swing.JTextField();
        destinationLabelEdit = new javax.swing.JLabel();
        cancelButtonEdit = new javax.swing.JButton();
        addressTextEdit = new javax.swing.JTextField();
        residenceLabelEdit = new javax.swing.JLabel();
        phoneTextEdit = new javax.swing.JTextField();
        addressLabelEdit = new javax.swing.JLabel();
        destinationTextEdit = new javax.swing.JTextField();
        postalCodeLabelEdit = new javax.swing.JLabel();
        lastNameLabelEdit = new javax.swing.JLabel();
        firstNameLabelEdit = new javax.swing.JLabel();
        emailTextEdit = new javax.swing.JTextField();
        headerLabelEditCust = new javax.swing.JLabel();
        saveButtonEdit = new javax.swing.JButton();
        customerIdLabelEdit = new javax.swing.JLabel();
        emailLabelEdit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTextPaneEdit = new javax.swing.JTextPane();
        firstNameTextEdit = new javax.swing.JTextField();
        customerIdTextEdit = new javax.swing.JTextField();
        notesLabelEdit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        postalCodeTextEdit.setName("postalText"); // NOI18N
        postalCodeTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTextEditActionPerformed(evt);
            }
        });

        lastNameTextEdit.setName("lnameText"); // NOI18N

        phoneLabelEdit.setText("Phone:");
        phoneLabelEdit.setName("phoneLabelEdit"); // NOI18N

        residenceTextEdit.setName("residenceTextEdit"); // NOI18N
        residenceTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residenceTextEditActionPerformed(evt);
            }
        });

        destinationLabelEdit.setText("Destination:");
        destinationLabelEdit.setName("destinationLabelEdit"); // NOI18N

        cancelButtonEdit.setText("Cancel");
        cancelButtonEdit.setName("cancelButtonEdit"); // NOI18N
        cancelButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonEditActionPerformed(evt);
            }
        });

        addressTextEdit.setName("addressTextEdit"); // NOI18N

        residenceLabelEdit.setText("Residence:");
        residenceLabelEdit.setName("residenceLabelEdit"); // NOI18N

        phoneTextEdit.setName("phoneTextEdit"); // NOI18N

        addressLabelEdit.setText("Address:");
        addressLabelEdit.setName("addressLabelEdit"); // NOI18N

        destinationTextEdit.setName("destinationTextEdit"); // NOI18N

        postalCodeLabelEdit.setText("Postal/ZIP:");
        postalCodeLabelEdit.setName("postalLabel"); // NOI18N

        lastNameLabelEdit.setText("Last name:");
        lastNameLabelEdit.setName("lnameLabel"); // NOI18N

        firstNameLabelEdit.setText("First name:");
        firstNameLabelEdit.setName("fnameLabel"); // NOI18N

        emailTextEdit.setName("emailTextEdit"); // NOI18N

        headerLabelEditCust.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        headerLabelEditCust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabelEditCust.setText("Edit costumer profile");
        headerLabelEditCust.setName("headerLabelEditCust"); // NOI18N

        saveButtonEdit.setText("Save");
        saveButtonEdit.setName("saveButtonEdit"); // NOI18N
        saveButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonEditActionPerformed(evt);
            }
        });

        customerIdLabelEdit.setText("Customer ID:");
        customerIdLabelEdit.setName("customeridLabel"); // NOI18N

        emailLabelEdit.setText("Email:");
        emailLabelEdit.setName("emailLabelEdit"); // NOI18N

        jScrollPane1.setName("notesText"); // NOI18N
        jScrollPane1.setViewportView(notesTextPaneEdit);

        firstNameTextEdit.setName("fnameText"); // NOI18N
        firstNameTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextEditActionPerformed(evt);
            }
        });

        customerIdTextEdit.setFocusable(false);
        customerIdTextEdit.setName("customeridText"); // NOI18N
        customerIdTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTextEditActionPerformed(evt);
            }
        });

        notesLabelEdit.setText("Notes:");
        notesLabelEdit.setName("notesLabelEdit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notesLabelEdit)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButtonEdit))
                            .addComponent(jScrollPane1)))
                    .addComponent(lastNameLabelEdit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameLabelEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(postalCodeLabelEdit))
                                    .addComponent(addressLabelEdit))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(customerIdLabelEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postalCodeTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerIdTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residenceLabelEdit)
                                    .addComponent(destinationLabelEdit)
                                    .addComponent(phoneLabelEdit)
                                    .addComponent(emailLabelEdit))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residenceTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destinationTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabelEditCust)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(headerLabelEditCust)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIdTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdLabelEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabelEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabelEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postalCodeTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalCodeLabelEdit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(residenceLabelEdit)
                            .addComponent(residenceTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destinationLabelEdit)
                            .addComponent(destinationTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabelEdit)
                            .addComponent(phoneTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabelEdit)
                            .addComponent(emailTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabelEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelEdit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButtonEdit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButtonEdit)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postalCodeTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeTextEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postalCodeTextEditActionPerformed

    private void residenceTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residenceTextEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residenceTextEditActionPerformed

    private void cancelButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonEditActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonEditActionPerformed

    private void saveButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonEditActionPerformed
        dispose(); //Moet worden veranderd naar een save
    }//GEN-LAST:event_saveButtonEditActionPerformed

    private void firstNameTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextEditActionPerformed

    private void customerIdTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCustomer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabelEdit;
    private javax.swing.JTextField addressTextEdit;
    private javax.swing.JButton cancelButtonEdit;
    private javax.swing.JLabel customerIdLabelEdit;
    private javax.swing.JTextField customerIdTextEdit;
    private javax.swing.JLabel destinationLabelEdit;
    private javax.swing.JTextField destinationTextEdit;
    private javax.swing.JLabel emailLabelEdit;
    private javax.swing.JTextField emailTextEdit;
    private javax.swing.JLabel firstNameLabelEdit;
    private javax.swing.JTextField firstNameTextEdit;
    private javax.swing.JLabel headerLabelEditCust;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabelEdit;
    private javax.swing.JTextField lastNameTextEdit;
    private javax.swing.JLabel notesLabelEdit;
    private javax.swing.JTextPane notesTextPaneEdit;
    private javax.swing.JLabel phoneLabelEdit;
    private javax.swing.JTextField phoneTextEdit;
    private javax.swing.JLabel postalCodeLabelEdit;
    private javax.swing.JTextField postalCodeTextEdit;
    private javax.swing.JLabel residenceLabelEdit;
    private javax.swing.JTextField residenceTextEdit;
    private javax.swing.JButton saveButtonEdit;
    // End of variables declaration//GEN-END:variables
}
