/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Edit;

/**
 *
 * @author Daan
 */
public final class EditAccount extends javax.swing.JFrame {

    /**
     * Creates new form EditAccount
     */
    public EditAccount() {
        initComponents();
        init();
    }
    
    public void init(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButtonEdit = new javax.swing.JButton();
        phoneLabel = new javax.swing.JLabel();
        saveButtonEdit = new javax.swing.JButton();
        residenceTextEdit = new javax.swing.JTextField();
        lastNameLabelEdit = new javax.swing.JLabel();
        idTextEdit = new javax.swing.JTextField();
        headerLabelEdit = new javax.swing.JLabel();
        phoneTextEdit = new javax.swing.JTextField();
        idLabelEdit = new javax.swing.JLabel();
        notesLabelEdit = new javax.swing.JLabel();
        firstNameLabelEdit = new javax.swing.JLabel();
        passwordTextEdit = new javax.swing.JTextField();
        passwordLabelEdit = new javax.swing.JLabel();
        accountLevelDropdownEdit = new javax.swing.JComboBox();
        firstNameTextEdit = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTextEdit = new javax.swing.JTextArea();
        emailTextEdit = new javax.swing.JTextField();
        accountLevelLabelEdit = new javax.swing.JLabel();
        lastNameTextEdit = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        residenceLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        postalCodeTextEdit = new javax.swing.JTextField();
        addressTextEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelButtonEdit.setText("Cancel");
        cancelButtonEdit.setName("cancelButtonEdit"); // NOI18N
        cancelButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonEditActionPerformed(evt);
            }
        });

        phoneLabel.setText("Phone:");
        phoneLabel.setName("manageridLabel"); // NOI18N

        saveButtonEdit.setText("Save");
        saveButtonEdit.setName("saveButtonEdit"); // NOI18N
        saveButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonEditActionPerformed(evt);
            }
        });

        residenceTextEdit.setName("residenceTextEdit"); // NOI18N

        lastNameLabelEdit.setText("Last name:");
        lastNameLabelEdit.setName("lastNameLabelEdit"); // NOI18N

        idTextEdit.setName("fnameText"); // NOI18N
        idTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextEditActionPerformed(evt);
            }
        });

        headerLabelEdit.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        headerLabelEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabelEdit.setText("Edit user account");
        headerLabelEdit.setName("headerLabelEdit"); // NOI18N

        phoneTextEdit.setName("manageridText"); // NOI18N

        idLabelEdit.setText("ID:");
        idLabelEdit.setName("fnameLabel"); // NOI18N

        notesLabelEdit.setText("Notes:");
        notesLabelEdit.setName("notesLabelEdit"); // NOI18N

        firstNameLabelEdit.setText("First name:");
        firstNameLabelEdit.setName("postalLabel"); // NOI18N

        passwordTextEdit.setName("lnameText"); // NOI18N

        passwordLabelEdit.setText("Password:");
        passwordLabelEdit.setName("lnameLabel"); // NOI18N

        accountLevelDropdownEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Manager", "Admin" }));
        accountLevelDropdownEdit.setToolTipText("User account level");

        firstNameTextEdit.setName("postalText"); // NOI18N

        postalCodeLabel.setText("Postal code:");
        postalCodeLabel.setName("postalCodeLabel"); // NOI18N

        notesTextEdit.setColumns(20);
        notesTextEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        notesTextEdit.setRows(5);
        jScrollPane1.setViewportView(notesTextEdit);

        accountLevelLabelEdit.setText("Account level:");

        emailLabel.setText("Email:");

        residenceLabel.setText("Place of residence:");
        residenceLabel.setName("residenceLabel"); // NOI18N

        addressLabel.setText("Address:");
        addressLabel.setName("addressLabel"); // NOI18N

        postalCodeTextEdit.setName("postalCodeTextEdit"); // NOI18N

        addressTextEdit.setName("addressTextEdit"); // NOI18N
        addressTextEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabelEdit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButtonEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabelEdit)
                                    .addComponent(passwordLabelEdit)
                                    .addComponent(accountLevelLabelEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passwordTextEdit)
                                    .addComponent(accountLevelDropdownEdit, 0, 166, Short.MAX_VALUE)
                                    .addComponent(idTextEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addressLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addressTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(postalCodeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(postalCodeTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(residenceLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(residenceTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabelEdit)
                                    .addComponent(lastNameLabelEdit)
                                    .addComponent(notesLabelEdit))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(firstNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(phoneLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lastNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emailLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailTextEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phoneTextEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(headerLabelEdit)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabelEdit)
                    .addComponent(idTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabelEdit)
                    .addComponent(passwordTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel)
                    .addComponent(postalCodeTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLevelDropdownEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountLevelLabelEdit)
                    .addComponent(residenceLabel)
                    .addComponent(residenceTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabelEdit)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameLabelEdit)
                        .addComponent(emailLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelEdit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButtonEdit)
                    .addComponent(cancelButtonEdit))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonEditActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonEditActionPerformed

    private void saveButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonEditActionPerformed
        dispose();
    }//GEN-LAST:event_saveButtonEditActionPerformed

    private void idTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextEditActionPerformed
        dispose();
    }//GEN-LAST:event_idTextEditActionPerformed

    private void addressTextEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountLevelDropdownEdit;
    private javax.swing.JLabel accountLevelLabelEdit;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextEdit;
    private javax.swing.JButton cancelButtonEdit;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextEdit;
    private javax.swing.JLabel firstNameLabelEdit;
    private javax.swing.JTextField firstNameTextEdit;
    private javax.swing.JLabel headerLabelEdit;
    private javax.swing.JLabel idLabelEdit;
    private javax.swing.JTextField idTextEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabelEdit;
    private javax.swing.JTextField lastNameTextEdit;
    private javax.swing.JLabel notesLabelEdit;
    private javax.swing.JTextArea notesTextEdit;
    private javax.swing.JLabel passwordLabelEdit;
    private javax.swing.JTextField passwordTextEdit;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextEdit;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JTextField postalCodeTextEdit;
    private javax.swing.JLabel residenceLabel;
    private javax.swing.JTextField residenceTextEdit;
    private javax.swing.JButton saveButtonEdit;
    // End of variables declaration//GEN-END:variables
}
