/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Edit;

import javax.swing.JFrame;

/**
 *
 * @author Daan
 */
public class EditLuggage extends javax.swing.JFrame {

    /**
     * Creates new form EditLuggage
     */
    public EditLuggage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButtonEdit = new javax.swing.JButton();
        saveButtonEdit = new javax.swing.JButton();
        bagTypeTextEdit = new javax.swing.JTextField();
        colorTextEdit = new javax.swing.JTextField();
        luggageIdTextEdit = new javax.swing.JTextField();
        statusLuggageEdit = new javax.swing.JLabel();
        luggageIdLabelEdit = new javax.swing.JLabel();
        CustomerIdLuggageEdit = new javax.swing.JLabel();
        colorLabelEdit = new javax.swing.JLabel();
        bagTypeLabelEdit = new javax.swing.JLabel();
        comboStatusEdit = new javax.swing.JComboBox();
        customerIdEdit = new javax.swing.JTextField();
        notesLabelEdit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesFieldLuggageEdit = new javax.swing.JTextArea();
        headerLabelEditLug = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cancelButtonEdit.setText("Cancel");
        cancelButtonEdit.setName("cancelButtonEdit"); // NOI18N
        cancelButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonEditActionPerformed(evt);
            }
        });

        saveButtonEdit.setText("Save");
        saveButtonEdit.setName("saveButtonEdit"); // NOI18N
        saveButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonEditActionPerformed(evt);
            }
        });

        bagTypeTextEdit.setName("bagtypeText"); // NOI18N

        colorTextEdit.setName("colorTextEdit"); // NOI18N

        luggageIdTextEdit.setFocusable(false);
        luggageIdTextEdit.setName("luggageidText"); // NOI18N

        statusLuggageEdit.setText("Status");

        luggageIdLabelEdit.setText("Luggage ID:");
        luggageIdLabelEdit.setName("luggageidLabel"); // NOI18N

        CustomerIdLuggageEdit.setText("Customer ID");

        colorLabelEdit.setText("Color:");
        colorLabelEdit.setName("colorLabelEdit"); // NOI18N

        bagTypeLabelEdit.setText("Bag type:");
        bagTypeLabelEdit.setName("bagtypeLabel"); // NOI18N

        comboStatusEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lost", "Found", "Seen", "Completed" }));

        notesLabelEdit.setText("Notes:");
        notesLabelEdit.setName("notesLabelEdit"); // NOI18N

        jScrollPane2.setPreferredSize(new java.awt.Dimension(50, 50));

        notesFieldLuggageEdit.setColumns(20);
        notesFieldLuggageEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        notesFieldLuggageEdit.setRows(4);
        notesFieldLuggageEdit.setWrapStyleWord(true);
        jScrollPane2.setViewportView(notesFieldLuggageEdit);

        headerLabelEditLug.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        headerLabelEditLug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabelEditLug.setText("Edit luggage profile");
        headerLabelEditLug.setName("headerLabelEditLug"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(headerLabelEditLug, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelEdit)
                    .addComponent(luggageIdLabelEdit)
                    .addComponent(colorLabelEdit)
                    .addComponent(bagTypeLabelEdit)
                    .addComponent(statusLuggageEdit)
                    .addComponent(CustomerIdLuggageEdit))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIdEdit)
                    .addComponent(comboStatusEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButtonEdit))
                    .addComponent(luggageIdTextEdit)
                    .addComponent(colorTextEdit)
                    .addComponent(bagTypeTextEdit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(headerLabelEditLug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luggageIdLabelEdit)
                    .addComponent(luggageIdTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabelEdit)
                    .addComponent(colorTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagTypeLabelEdit)
                    .addComponent(bagTypeTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLuggageEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerIdLuggageEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelEdit)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButtonEdit)
                    .addComponent(cancelButtonEdit))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonEditActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonEditActionPerformed

    private void saveButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonEditActionPerformed
        dispose(); //Alleen voor de presentatie, moet worden veranderd in save
    }//GEN-LAST:event_saveButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditLuggage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerIdLuggageEdit;
    private javax.swing.JLabel bagTypeLabelEdit;
    private javax.swing.JTextField bagTypeTextEdit;
    private javax.swing.JButton cancelButtonEdit;
    private javax.swing.JLabel colorLabelEdit;
    private javax.swing.JTextField colorTextEdit;
    private javax.swing.JComboBox comboStatusEdit;
    private javax.swing.JTextField customerIdEdit;
    private javax.swing.JLabel headerLabelEditLug;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel luggageIdLabelEdit;
    private javax.swing.JTextField luggageIdTextEdit;
    private javax.swing.JTextArea notesFieldLuggageEdit;
    private javax.swing.JLabel notesLabelEdit;
    private javax.swing.JButton saveButtonEdit;
    private javax.swing.JLabel statusLuggageEdit;
    // End of variables declaration//GEN-END:variables
}
