/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Create;

/**
 *
 * @author Jasper
 */
public class CreateLuggage extends javax.swing.JFrame {

    /**
     * Creates new form CreateLuggage
     */
    public CreateLuggage() {
        initComponents();
        init();
    }

    public void init() {
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabelCreateLug = new javax.swing.JLabel();
        luggageIdLabelCreate = new javax.swing.JLabel();
        colorLabelCreate = new javax.swing.JLabel();
        bagTypeLabelCreate = new javax.swing.JLabel();
        notesLabelCreate = new javax.swing.JLabel();
        luggageIdTextCreate = new javax.swing.JTextField();
        colorTextCreate = new javax.swing.JTextField();
        bagTypeTextCreate = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesFieldLuggageCreate = new javax.swing.JTextArea();
        comboStatusCreate = new javax.swing.JComboBox();
        customerIdCreate = new javax.swing.JTextField();
        statusLuggageCreate = new javax.swing.JLabel();
        customerIdCreateLuggage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create luggage profile");
        setName("createLuggage"); // NOI18N

        headerLabelCreateLug.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        headerLabelCreateLug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabelCreateLug.setText("Create luggage profile");
        headerLabelCreateLug.setName("headerLabelCreateLug"); // NOI18N

        luggageIdLabelCreate.setText("Luggage ID:");
        luggageIdLabelCreate.setName("luggageidLabel"); // NOI18N

        colorLabelCreate.setText("Color:");
        colorLabelCreate.setName("colorLabelCreate"); // NOI18N

        bagTypeLabelCreate.setText("Bag type:");
        bagTypeLabelCreate.setName("bagtypeLabel"); // NOI18N

        notesLabelCreate.setText("Notes:");
        notesLabelCreate.setName("notesLabelCreate"); // NOI18N

        luggageIdTextCreate.setFocusable(false);
        luggageIdTextCreate.setName("luggageidText"); // NOI18N

        colorTextCreate.setName("colorTextCreate"); // NOI18N

        bagTypeTextCreate.setName("bagtypeText"); // NOI18N

        saveButton.setText("Save");
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(50, 50));

        notesFieldLuggageCreate.setColumns(20);
        notesFieldLuggageCreate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        notesFieldLuggageCreate.setRows(4);
        notesFieldLuggageCreate.setWrapStyleWord(true);
        jScrollPane2.setViewportView(notesFieldLuggageCreate);

        comboStatusCreate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lost", "Found", "Seen", "Completed" }));

        statusLuggageCreate.setText("Status");

        customerIdCreateLuggage.setText("Customer ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(headerLabelCreateLug, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelCreate)
                    .addComponent(luggageIdLabelCreate)
                    .addComponent(colorLabelCreate)
                    .addComponent(bagTypeLabelCreate)
                    .addComponent(statusLuggageCreate)
                    .addComponent(customerIdCreateLuggage))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIdCreate)
                    .addComponent(comboStatusCreate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addComponent(luggageIdTextCreate)
                    .addComponent(colorTextCreate)
                    .addComponent(bagTypeTextCreate)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(headerLabelCreateLug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luggageIdLabelCreate)
                    .addComponent(luggageIdTextCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabelCreate)
                    .addComponent(colorTextCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagTypeLabelCreate)
                    .addComponent(bagTypeTextCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatusCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLuggageCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdCreateLuggage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabelCreate)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        dispose(); //Alleen voor de presentatie, moet worden veranderd in save
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLuggage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLuggage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bagTypeLabelCreate;
    private javax.swing.JTextField bagTypeTextCreate;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel colorLabelCreate;
    private javax.swing.JTextField colorTextCreate;
    private javax.swing.JComboBox comboStatusCreate;
    private javax.swing.JTextField customerIdCreate;
    private javax.swing.JLabel customerIdCreateLuggage;
    private javax.swing.JLabel headerLabelCreateLug;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel luggageIdLabelCreate;
    private javax.swing.JTextField luggageIdTextCreate;
    private javax.swing.JTextArea notesFieldLuggageCreate;
    private javax.swing.JLabel notesLabelCreate;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel statusLuggageCreate;
    // End of variables declaration//GEN-END:variables
}
